package com.stadio.model.enu;

public enum ConfigKey {

    FIRE_BASE_API,
    MAX_FAST_PRACTICE,
    PRICE_FAST_PRACTICE,
    MODE_PAYMENT,
    ANDROID_MIN_VERSION,
    ANDROID_CURRENT_VERSION,
    ANDROID_UPDATE_URL,
    IOS_MIN_VERSION,
    IOS_CURRENT_VERSION,
    IOS_UPDATE_URL,
    FACEBOOK_GROUP,
    FACEBOOK_PAGE,
    WEBSITE_URL,
    CMS_NAV_BAR,
    ALLOW_REGISTER
}
